export const results = [
  {
    mal_id: 20,
    url: '',
    image_url: './assets/115154.jpg',
    title: 'Naruto',
    airing: true,
    synopsis:
      "Moments prior to Naruto Uzumaki's birth, a huge demon known as the Kyuubi, the Nine-Tailed Fox, attacked Konohagakure, the Hidden Leaf Village, and wreaked havoc. In order rto put an end to the Kyuubi...",
    type: 'TV',
    episodes: 220,
    score: 7.92,
    start_date: '',
    end_date: '',
    members: 2026379,
    rated: 'PG-13',
  },
  {
    mal_id: 120,
    url: '',
    image_url: './assets/114792.jpg',
    title: 'Fruits Basket',
    airing: false,
    synopsis:
      'After the accident in which she lost her mother, 16-year old Tooru moves in with her grandfather, but due to his home being renovated, is unable to continue livi...',
    type: 'TV',
    episodes: 26,
    score: 7.69,
    start_date: '',
    end_date: '',
    members: 448679,
    rated: 'PG-13',
  },
  {
    mal_id: 30,
    url: '',
    image_url: './assets/115154.jpg',
    title: 'Naruto 1',
    airing: false,
    synopsis:
      "Moments prior to Naruto Uzumaki's birth, a huge demon known as the Kyuubi, the Nine-Tailed Fox, attacked Konohagakure, the Hidden Leaf Village, and wreaked havoc. In order rto put an end to the Kyuubi...",
    type: 'TV',
    episodes: 220,
    score: 7.92,
    start_date: '',
    end_date: '',
    members: 2026379,
    rated: 'PG-13',
  },
  {
    mal_id: 40417,
    url: '',
    image_url: './assets/114792.jpg',
    title: 'Fruits Basket 1',
    airing: false,
    synopsis:
      'After the accident in which she lost her mother, 16-year old Tooru moves in with her grandfather, but due to his home being renovated, is unable to continue livi...',
    type: 'TV',
    episodes: 26,
    score: 7.69,
    start_date: '',
    end_date: '',
    members: 448679,
    rated: 'PG-13',
  },
  {
    mal_id: 40,
    url: '',
    image_url: './assets/115154.jpg',
    title: 'Naruto 2',
    airing: false,
    synopsis:
      "Moments prior to Naruto Uzumaki's birth, a huge demon known as the Kyuubi, the Nine-Tailed Fox, attacked Konohagakure, the Hidden Leaf Village, and wreaked havoc. In order rto put an end to the Kyuubi...",
    type: 'TV',
    episodes: 220,
    score: 7.92,
    start_date: '',
    end_date: '',
    members: 2026379,
    rated: 'PG-13',
  },
  {
    mal_id: 140,
    url: '',
    image_url: './assets/114792.jpg',
    title: 'Fruits Basket 2',
    airing: false,
    synopsis:
      'After the accident in which she lost her mother, 16-year old Tooru moves in with her grandfather, but due to his home being renovated, is unable to continue livi...',
    type: 'TV',
    episodes: 26,
    score: 7.69,
    start_date: '',
    end_date: '',
    members: 448679,
    rated: 'PG-13',
  },
];

// airing false, rank 85, popularity 613, score 8.55

export const animeDetails = {
  mal_id: 40417,
  url: '',
  image_url: '/assets/114792.jpg',
  trailer_url: '',
  title: 'Fruits Basket 2nd Season',
  title_english: 'Fruits Basket S2',
  title_japanese: '2nd Season',
  title_synonyms: [
    'Fruits Basket (2019) 2nd Season',
    'Furuba',
    'Fruits Basket (Zenpen)',
  ],
  type: 'TV',
  source: 'Manga',
  episodes: 25,
  status: 'Finished Airing',
  airing: true,
  aired: {},
  duration: '23 min per ep',
  rating: 'PG-13 - Teens 13 or older',
  score: 8.55,
  scored_by: 101137,
  rank: 85,
  popularity: 613,
  members: 256735,
  favorites: 3585,
  synopsis:
    "A year has passed since Tooru Honda began living in the Souma residence, and she has since created stronger relationships with its inhabitants Shigure, Kyou, and Yuki. She has also grown closer to the rest of the Souma family and has become familiar with their ancestral secet, having helped them with many of their personal issues. The closer Tooru gets, the more she begins to realize that their secret holds a darker truth than she first presumed. Summer is approaching and Tooru is invited to spend her days with the Soumas, mainly Kyou and Yuki. Tooru wishes for an easy-going vacation, but her close relationships with the two boys and the rest of the Soumas may prove to cause trouble. As they grow more intimate, their carefree time together is hindered by older hardships and feelings from the past that begin to resurface. The Eternal Banquet also dawns on the members of the zodiac, and they must tend to their duties alongside the unnerving head of the family, Akito Souma. With the banquet approaching and a plethora of feelings to be solved, will Toorus's life with the Soumas remain peaceful, or will she find herself in a situation from which she cannot escape? [Written by MAL Rewrite]",
  background: null,
  premiered: 'Spring 2020',
  broadcast: 'Tuesdays at 01:30 (JST)',
  related: {
    Adaptation: [
      {
        mal_id: 102,
        type: 'manga',
        name: 'Fruits Basket',
        url: '',
      },
    ],
    Prequel: [
      {
        mal_id: 38680,
        type: 'anime',
        name: 'Fruits Basket 1st Season',
        url: '',
      },
    ],
    Sequel: [
      {
        mal_id: 42938,
        type: 'anime',
        name: 'Fruits Basket: The Final',
        url: '',
      },
    ],
    Other: [
      {
        mal_id: 40421,
        type: 'anime',
        name: 'Fruits Basket Ova',
        url: '',
      },
    ],
  },
  producers: [
    {
      mal_id: 2174,
      type: 'anime',
      name: 'TMS Music',
      url: '',
    },
  ],
  licensors: [
    {
      mal_id: 102,
      type: 'anime',
      name: 'Funimation',
      url: '',
    },
  ],
  studios: [
    {
      mal_id: 73,
      type: 'anime',
      name: 'TMS Entertainment',
      url: '',
    },
  ],
  genres: [
    {
      mal_id: 36,
      type: 'anime',
      name: 'Slice of Life',
      url: '',
    },
    {
      mal_id: 4,
      type: 'anime',
      name: 'Comedy',
      url: '',
    },
    {
      mal_id: 37,
      type: 'anime',
      name: 'Supernatural',
      url: '',
    },
    {
      mal_id: 8,
      type: 'anime',
      name: 'Drama',
      url: '',
    },
    {
      mal_id: 22,
      type: 'anime',
      name: 'Romance',
      url: '',
    },
    {
      mal_id: 25,
      type: 'anime',
      name: 'Shoujo',
      url: '',
    },
  ],
  opening_themes: [
    '#1: "Prism" by AmPm ft. Miyuna (eps 1-13)',
    '#2: "HOME" by Asako Toki (JapChar) (eps 14-25)',
  ],
  ending_themes: [
    '#1: "ad meliora" by THE CHARM PARK (eps 1-6, 8-13)',
    '#2: "Haseru Mirai (JapChar)" by Uta Arii (JapChar) (ep 7)',
    '#3: "Eden" by MONKEY MAJIK (eps 14-25)',
  ],
};
